#!/usr/bin/env bash
set -euo pipefail

usage()
{
cat << EOF
usage: $0 [--output DIR] [--vlc-root DIR] [--evidence-root DIR]

Extract license notices for the VLCKit binary package.

The script is intended to run after libVLC has been built. It uses the
static-libs-list files generated by the Apple libVLC build to record which
VLC libraries, plugins, and contrib static libraries were linked into
libvlc-full-static.a, then collects available license-like files from the
corresponding source and build directories.
EOF
}

script_dir="$(cd "${BASH_SOURCE%/*}"; pwd)"
project_root="$(cd "$script_dir/.."; pwd)"
output_dir="$project_root/build/license-notices"
vlc_root="$project_root/libvlc/vlc"
evidence_root=""

while [ "$#" -gt 0 ]; do
    case "$1" in
        --output=*)
            output_dir="${1#--output=}"
            ;;
        --output)
            shift
            output_dir="$1"
            ;;
        --vlc-root=*)
            vlc_root="${1#--vlc-root=}"
            ;;
        --vlc-root)
            shift
            vlc_root="$1"
            ;;
        --evidence-root=*)
            evidence_root="${1#--evidence-root=}"
            ;;
        --evidence-root)
            shift
            evidence_root="$1"
            ;;
        --help|-h)
            usage
            exit 0
            ;;
        *)
            echo "Unknown option: $1" >&2
            usage >&2
            exit 1
            ;;
    esac
    shift
done

mkdir -p "$output_dir"
output_dir="$(cd "$output_dir"; pwd)"
rm -rf "$output_dir/licenses" \
       "$output_dir/manifests" \
       "$output_dir/README.txt" \
       "$output_dir/VLCKit-LICENSES-THIRD-PARTY.txt"
mkdir -p "$output_dir/licenses" "$output_dir/manifests"

combined_notice="$output_dir/VLCKit-LICENSES-THIRD-PARTY.txt"
build_info="$output_dir/manifests/build-info.txt"
static_libs_all="$output_dir/manifests/static-libs-list-all.txt"
contrib_manifest="$output_dir/manifests/contrib-static-libraries.tsv"
linked_contrib_packages="$output_dir/manifests/linked-contrib-packages.txt"
plugin_manifest="$output_dir/manifests/vlc-static-plugins.txt"
license_files_manifest="$output_dir/manifests/license-files.tsv"
candidate_license_files_manifest="$output_dir/manifests/candidate-license-files.tsv"
binary_evidence_files_manifest="$output_dir/manifests/binary-evidence-files.txt"
nested_dependency_evidence_manifest="$output_dir/manifests/nested-dependency-evidence.tsv"
skipped_unlinked_notice_files_manifest="$output_dir/manifests/skipped-unlinked-license-files.tsv"
skipped_gpl_notice_files_manifest="$output_dir/manifests/skipped-gpl-license-files.tsv"
skipped_nonruntime_notice_files_manifest="$output_dir/manifests/skipped-nonruntime-license-files.tsv"
gpl_only_linked_notice_failures="$output_dir/manifests/gpl-only-linked-license-failures.tsv"
seen_notice_keys="$output_dir/manifests/.seen-license-files"
binary_evidence_strings="$output_dir/manifests/.binary-evidence-strings"
binary_evidence_cache="$output_dir/manifests/.binary-evidence-cache"

: > "$static_libs_all"
: > "$contrib_manifest"
: > "$linked_contrib_packages"
: > "$plugin_manifest"
: > "$license_files_manifest"
: > "$candidate_license_files_manifest"
: > "$binary_evidence_files_manifest"
: > "$nested_dependency_evidence_manifest"
: > "$skipped_unlinked_notice_files_manifest"
: > "$skipped_gpl_notice_files_manifest"
: > "$skipped_nonruntime_notice_files_manifest"
: > "$gpl_only_linked_notice_failures"
: > "$seen_notice_keys"
: > "$binary_evidence_strings"
: > "$binary_evidence_cache"

sanitize_name()
{
    printf '%s' "$1" | sed 's#[/:][/:]*#-#g; s#[^A-Za-z0-9._+-]#-#g'
}

copy_notice_file()
{
    local source_file="$1"
    local label="$2"

    if [ ! -f "$source_file" ]; then
        return 0
    fi

    local package
    package="$(infer_package_name "$source_file" "$label")"
    package="$(normalize_package_name "$package")"

    local nested_package=""
    if nested_package="$(nested_dependency_name "$source_file")"; then
        nested_package="$(normalize_package_name "$nested_package")"
        package="$nested_package"
    fi

    if is_gpl_only_notice_file "$source_file" "$label"; then
        printf '%s\t%s\t%s\n' "$package" "$(relative_to_project "$source_file")" "GPL-only notice excluded for --disable-gpl builds" >> "$skipped_gpl_notice_files_manifest"
        return 0
    fi

    if is_nonruntime_notice_file "$source_file" "$label"; then
        printf '%s\t%s\t%s\n' "$package" "$(relative_to_project "$source_file")" "non-runtime documentation notice excluded" >> "$skipped_nonruntime_notice_files_manifest"
        return 0
    fi

    if [ -n "$nested_package" ]; then
        if package_is_linked "$nested_package"; then
            printf '%s\t%s\t%s\n' "$nested_package" "$(relative_to_project "$source_file")" "linked contrib package" >> "$nested_dependency_evidence_manifest"
        elif nested_dependency_has_binary_evidence "$source_file" "$nested_package"; then
            printf '%s\t%s\t%s\n' "$nested_package" "$(relative_to_project "$source_file")" "binary or dSYM evidence" >> "$nested_dependency_evidence_manifest"
            package="$nested_package"
        else
            printf '%s\t%s\t%s\n' "$nested_package" "$(relative_to_project "$source_file")" "nested dependency not present in linked-contrib-packages.txt or binary evidence" >> "$skipped_unlinked_notice_files_manifest"
            return 0
        fi
    fi

    local target_path
    target_path="$(license_target_relative_path "$source_file" "$package")"

    local key
    key="$(notice_dedupe_key "$source_file" "$target_path")"
    if grep -Fqx "$key" "$seen_notice_keys"; then
        return 0
    fi
    printf '%s\n' "$key" >> "$seen_notice_keys"

    mkdir -p "$output_dir/$(dirname "$target_path")"
    if [ -s "$output_dir/$target_path" ]; then
        printf '\n\n' >> "$output_dir/$target_path"
    fi
    cat "$source_file" >> "$output_dir/$target_path"
    printf '%s\t%s\t%s\n' "$package" "$(relative_to_project "$source_file")" "$target_path" >> "$license_files_manifest"
}

is_gpl_only_notice_file()
{
    local source_file="$1"
    local label="$2"
    local name
    local header

    name="$(printf '%s %s' "${source_file##*/}" "$label" | LC_ALL=C tr '[:lower:]' '[:upper:]')"
    case "$name" in
        *LGPL*|*LESSER*|*LIBRARY-GPL*|*LIBRARY_GPL*)
            return 1
            ;;
        *GPL*)
            return 0
            ;;
    esac

    header="$(sed -n '1,12p' "$source_file" | LC_ALL=C tr '[:lower:]' '[:upper:]')"
    case "$header" in
        *"GNU LESSER GENERAL PUBLIC LICENSE"*|*"GNU LIBRARY GENERAL PUBLIC LICENSE"*)
            return 1
            ;;
        *"GNU GENERAL PUBLIC LICENSE"*|*"GNU AFFERO GENERAL PUBLIC LICENSE"*)
            return 0
            ;;
    esac

    return 1
}

is_nonruntime_notice_file()
{
    local source_file="$1"
    local label="$2"
    local name

    name="$(printf '%s %s' "${source_file##*/}" "$label" | LC_ALL=C tr '[:lower:]' '[:upper:]')"
    case "$name" in
        *FDL*)
            return 0
            ;;
    esac

    return 1
}

is_notice_file()
{
    local file
    file="${1##*/}"

    case "$file" in
        COPYING|COPYING.*|LICENSE|LICENSE.*|License.txt|license.txt|NOTICE|NOTICE.*|Copyright|COPYRIGHT|Copyright.*|COPYRIGHT.*)
            return 0
            ;;
    esac

    return 1
}

path_has_single_component()
{
    case "$1" in
        ""|*/*)
            return 1
            ;;
        *)
            return 0
            ;;
    esac
}

nested_dependency_info_from_rest()
{
    local rest="$1"

    printf '%s\n' "$rest" | awk -F/ '
        BEGIN {
            split("third_party thirdparty third-party 3rdparty contrib", markers, " ")
            for (i in markers) {
                marker[markers[i]] = 1
            }
        }
        {
            for (i = 1; i < NF; i++) {
                if (($i in marker) && $(i + 1) != "") {
                    remainder = ""
                    for (j = i + 2; j <= NF; j++) {
                        if (remainder != "") {
                            remainder = remainder "/"
                        }
                        remainder = remainder $j
                    }
                    print $i "/" $(i + 1) "\t" $(i + 1) "\t" remainder
                    exit 0
                }
            }
            exit 1
        }
    '
}

nested_dependency_remainder()
{
    local rest="$1"
    local info

    info="$(nested_dependency_info_from_rest "$rest")" || return 1
    printf '%s\n' "$info" | awk -F '\t' '{ print $3 }'
}

is_collectable_notice_file()
{
    local source_file="$1"
    local relative_path
    local rest
    local nested_rest

    if ! is_notice_file "$source_file"; then
        return 1
    fi

    relative_path="$(source_relative_to_vlc_root "$source_file")"
    case "$relative_path" in
        contrib/src/*|contrib/tarballs/*|*"/share/doc/"*)
            return 1
            ;;
    esac

    rest="$(source_path_after_package "$relative_path")"
    if path_has_single_component "$rest"; then
        return 0
    fi

    if nested_rest="$(nested_dependency_remainder "$rest")" && path_has_single_component "$nested_rest"; then
        return 0
    fi

    return 1
}

relative_to_project()
{
    local path="$1"
    case "$path" in
        "$project_root"/*)
            printf '%s' "${path#"$project_root"/}"
            ;;
        *)
            printf '%s' "$path"
            ;;
    esac
}

relative_to_vlc_root()
{
    local path="$1"
    case "$path" in
        "$vlc_root"/*)
            printf '%s' "${path#"$vlc_root"/}"
            return 0
            ;;
        *)
            return 1
            ;;
    esac
}

infer_package_name()
{
    local source_file="$1"
    local label="$2"
    local relative_path
    local vlc_relative_path
    relative_path="$(relative_to_project "$source_file")"
    if vlc_relative_path="$(relative_to_vlc_root "$source_file")"; then
        relative_path="$vlc_relative_path"
    fi

    case "$label" in
        VLCKit-*)
            echo "VLCKit"
            return 0
            ;;
        VLC-*)
            echo "VLC"
            return 0
            ;;
    esac

    case "$relative_path" in
        *"/share/doc/"*)
            echo "$relative_path" | awk -F'/share/doc/' '{ print $2 }' | awk -F/ '{ print $1 }' | sed 's#[^A-Za-z0-9._+-]#-#g'
            return 0
            ;;
        *"/contrib/contrib-"*|contrib/contrib-*)
            echo "/$relative_path" | awk -F'/contrib/contrib-' '{ print $2 }' | awk -F/ '{ print $2 }' | sed 's#[^A-Za-z0-9._+-]#-#g'
            return 0
            ;;
        */*)
            echo "$relative_path" | awk -F/ '{ print $1 }' | sed 's#[^A-Za-z0-9._+-]#-#g'
            return 0
            ;;
        libvlc/vlc/*/*)
            echo "$relative_path" | awk -F/ '{ print $3 }' | sed 's#[^A-Za-z0-9._+-]#-#g'
            return 0
            ;;
    esac

    echo "unknown"
}

license_target_relative_path()
{
    local _source_file="$1"
    local package="$2"

    printf 'licenses/%s.txt\n' "$(sanitize_name "$package")"
}

nested_dependency_name()
{
    local source_file="$1"
    local relative_path
    local rest
    local info

    relative_path="$(source_relative_to_vlc_root "$source_file")"
    rest="$(source_path_after_package "$relative_path")"
    info="$(nested_dependency_info_from_rest "$rest")" || return 1
    printf '%s\n' "$info" | awk -F '\t' '{ print $2 }'
}

source_relative_to_vlc_root()
{
    local source_file="$1"
    local relative_path
    local vlc_relative_path

    relative_path="$(relative_to_project "$source_file")"
    if vlc_relative_path="$(relative_to_vlc_root "$source_file")"; then
        relative_path="$vlc_relative_path"
    fi

    printf '%s\n' "$relative_path"
}

source_path_after_package()
{
    local relative_path="$1"

    case "$relative_path" in
        *"/share/doc/"*)
            printf '%s\n' "$relative_path" | awk -F'/share/doc/' '{ print $2 }' | cut -d/ -f2-
            return 0
            ;;
        *"/contrib/contrib-"*|contrib/contrib-*)
            printf '%s\n' "/$relative_path" | awk -F'/contrib/contrib-' '{ print $2 }' | cut -d/ -f3-
            return 0
            ;;
        libvlc/vlc/*/*)
            printf '%s\n' "$relative_path" | cut -d/ -f4-
            return 0
            ;;
        */*)
            printf '%s\n' "$relative_path" | cut -d/ -f2-
            return 0
            ;;
    esac

    printf '%s\n' "$relative_path"
}

nested_dependency_has_binary_evidence()
{
    local source_file="$1"
    local nested_package="$2"
    local marker
    local cached

    if [ ! -s "$binary_evidence_strings" ]; then
        return 1
    fi

    marker="$(nested_dependency_marker "$source_file")"
    cached="$(awk -F '\t' -v package="$nested_package" -v marker="$marker" \
        '$1 == package && $2 == marker { print $3; exit }' "$binary_evidence_cache")"
    if [ "$cached" = "present" ]; then
        return 0
    fi
    if [ "$cached" = "absent" ]; then
        return 1
    fi

    if nested_dependency_has_binary_evidence_uncached "$nested_package" "$marker"; then
        printf '%s\t%s\t%s\n' "$nested_package" "$marker" "present" >> "$binary_evidence_cache"
        return 0
    fi

    printf '%s\t%s\t%s\n' "$nested_package" "$marker" "absent" >> "$binary_evidence_cache"
    return 1
}

nested_dependency_has_binary_evidence_uncached()
{
    local nested_package="$1"
    local marker="$2"

    if [ -n "$marker" ] && grep -Fqi "$marker" "$binary_evidence_strings"; then
        return 0
    fi

    case "$nested_package" in
        ""|*[!A-Za-z0-9_-]*)
            return 1
            ;;
    esac

    if [ "${#nested_package}" -lt 5 ]; then
        return 1
    fi

    grep -Fqi "${nested_package}_" "$binary_evidence_strings" \
        || grep -Fqi "${nested_package}-" "$binary_evidence_strings"
}

nested_dependency_marker()
{
    local source_file="$1"
    local relative_path
    local rest
    local info

    relative_path="$(source_relative_to_vlc_root "$source_file")"
    rest="$(source_path_after_package "$relative_path")"
    info="$(nested_dependency_info_from_rest "$rest")" || return 1
    printf '%s\n' "$info" | awk -F '\t' '{ print $1 }'
}

notice_dedupe_key()
{
    local source_file="$1"
    local target_path="$2"
    local relative_path
    local vlc_relative_path

    relative_path="$(relative_to_project "$source_file")"
    if vlc_relative_path="$(relative_to_vlc_root "$source_file")"; then
        relative_path="$vlc_relative_path"
    fi

    case "$relative_path" in
        *"/contrib/"*|contrib/*)
            relative_path="$(printf '%s\n' "/$relative_path" | awk '
                {
                    marker = "/contrib/"
                    start = index($0, marker)
                    if (start == 0) {
                        print $0
                        next
                    }
                    prefix = substr($0, 1, start + length(marker) - 1)
                    rest = substr($0, start + length(marker))
                    count = split(rest, parts, "/")
                    rest_without_triplet = ""
                    for (i = 2; i <= count; i++) {
                        if (rest_without_triplet != "") {
                            rest_without_triplet = rest_without_triplet "/"
                        }
                        rest_without_triplet = rest_without_triplet parts[i]
                    }
                    print prefix rest_without_triplet
                }
            ')"
            ;;
    esac

    printf '%s\t%s\n' "$target_path" "$relative_path"
}

normalize_package_name()
{
    case "$1" in
        libass) echo "ass" ;;
        libssh2) echo "ssh2" ;;
        libshout) echo "shout" ;;
        libpng|libpng16) echo "png" ;;
        libaom) echo "aom" ;;
        FLAC|libFLAC|libflac) echo "flac" ;;
        libgsm) echo "gsm" ;;
        xml2) echo "libxml2" ;;
        libjpeg|jpeg-turbo) echo "jpeg" ;;
        libfreetype|freetype) echo "freetype2" ;;
        libvorbis|libvorbisenc|libvorbisfile) echo "vorbis" ;;
        libtheora|libtheoradec|libtheoraenc) echo "theora" ;;
        libspeex) echo "speex" ;;
        libspeexdsp) echo "speexdsp" ;;
        *)
            printf '%s\n' "$1"
            ;;
    esac
}

package_from_static_library()
{
    local library="$1"
    local stem

    stem="${library##*/}"
    stem="${stem%.a}"

    case "$stem" in
        libavcodec|libavformat|libavutil|libswscale)
            echo "ffmpeg"
            ;;
        libBasicUsageEnvironment|libgroupsock|libliveMedia|libUsageEnvironment)
            echo "live555"
            ;;
        libGenericCodeGen|libglslang|libglslang-default-resource-limits|libHLSL|libMachineIndependent|libOGLCompiler|libOSDependent|libSPIRV|libSPVRemapper)
            echo "glslang"
            ;;
        libharfbuzz|libharfbuzz-subset)
            echo "harfbuzz"
            ;;
        libiconv|libcharset)
            echo "iconv"
            ;;
        libixml|libupnp)
            echo "upnp"
            ;;
        libmp3lame)
            echo "lame"
            ;;
        libmpg123|libout123|libsyn123)
            echo "mpg123"
            ;;
        liboapv)
            echo "openapv"
            ;;
        libopenjp2)
            echo "openjpeg"
            ;;
        libprotobuf|libprotobuf-lite)
            echo "protobuf"
            ;;
        libprotoc)
            echo "protoc"
            ;;
        libtag)
            echo "taglib"
            ;;
        libz)
            echo "zlib"
            ;;
        *)
            normalize_package_name "$stem"
            if [ "$stem" != "${stem#lib}" ]; then
                normalize_package_name "${stem#lib}"
            fi
            ;;
    esac
}

package_is_linked()
{
    local package
    package="$(normalize_package_name "$1")"

    if [ ! -s "$linked_contrib_packages" ]; then
        return 0
    fi

    grep -Fxq "$package" "$linked_contrib_packages"
}

build_binary_evidence_index()
{
    local root="$1"

    if [ -z "$root" ] || [ ! -d "$root" ]; then
        return 0
    fi

    while IFS= read -r evidence_file; do
        if ! is_binary_evidence_file "$evidence_file"; then
            continue
        fi

        printf '%s\n' "$(relative_to_project "$evidence_file")" >> "$binary_evidence_files_manifest"
        {
            printf '\n# %s\n' "$evidence_file"
            strings -a "$evidence_file" 2>/dev/null || true
        } >> "$binary_evidence_strings"
    done < <(
        find "$root" -type f \
            \( -path '*/Contents/Resources/DWARF/*' \
            -o -path '*.framework/*' \) \
            | sort
    )
}

is_binary_evidence_file()
{
    local path="$1"
    local file
    local parent
    local framework_part
    local framework_name

    case "$path" in
        */Contents/Resources/DWARF/*)
            return 0
            ;;
    esac

    file="${path##*/}"
    parent="${path%/*}"

    case "$parent" in
        *.framework)
            framework_name="${parent##*/}"
            framework_name="${framework_name%.framework}"
            [ "$file" = "$framework_name" ]
            return
            ;;
    esac

    case "$path" in
        */*.framework/Versions/*/*)
            framework_part="${path%%.framework/Versions/*}.framework"
            framework_name="${framework_part##*/}"
            framework_name="${framework_name%.framework}"
            [ "$file" = "$framework_name" ]
            return
            ;;
    esac

    return 1
}

package_has_accepted_notice()
{
    local package="$1"

    package="$(normalize_package_name "$package")"
    awk -F '\t' -v package="$package" '$1 == package { found = 1 } END { exit !found }' "$license_files_manifest"
}

notice_is_required_for_build()
{
    local source_file="$1"
    local package="$2"
    local nested_package

    case "$package" in
        VLCKit|VLC)
            return 0
            ;;
    esac

    if [ -s "$linked_contrib_packages" ] && package_is_linked "$package"; then
        return 0
    fi

    if nested_package="$(nested_dependency_name "$source_file")"; then
        nested_package="$(normalize_package_name "$nested_package")"
        if [ -s "$linked_contrib_packages" ] && package_is_linked "$nested_package"; then
            return 0
        fi
        if nested_dependency_has_binary_evidence "$source_file" "$nested_package"; then
            return 0
        fi
    fi

    return 1
}

verify_no_gpl_only_linked_notice_gaps()
{
    local package
    local source_file
    local reason

    : > "$gpl_only_linked_notice_failures"

    while IFS="$(printf '\t')" read -r package source_file reason; do
        if [ -z "$package" ] || [ -z "$source_file" ]; then
            continue
        fi

        if notice_is_required_for_build "$source_file" "$package" && ! package_has_accepted_notice "$package"; then
            printf '%s\t%s\t%s\n' "$package" "$source_file" "GPL-only notice belongs to a linked/evidenced package, but no non-GPL notice was copied" >> "$gpl_only_linked_notice_failures"
        fi
    done < "$skipped_gpl_notice_files_manifest"

    if [ -s "$gpl_only_linked_notice_failures" ]; then
        echo "error: GPL-only linked license gap detected" >&2
        echo "The following linked/evidenced packages only had GPL-only notices copied out:" >&2
        cat "$gpl_only_linked_notice_failures" >&2
        exit 1
    fi
}

process_candidate_notice_file()
{
    local notice_file="$1"
    local rel
    local package
    local notice_package
    local nested_package

    rel="$(relative_to_project "$notice_file")"
    package="$(infer_package_name "$notice_file" "$rel")"
    package="$(normalize_package_name "$package")"
    printf '%s\t%s\n' "$package" "$rel" >> "$candidate_license_files_manifest"

    notice_package="$package"
    if nested_package="$(nested_dependency_name "$notice_file")"; then
        notice_package="$(normalize_package_name "$nested_package")"
    fi

    if is_gpl_only_notice_file "$notice_file" "$rel"; then
        printf '%s\t%s\t%s\n' "$notice_package" "$rel" "GPL-only notice excluded for --disable-gpl builds" >> "$skipped_gpl_notice_files_manifest"
        return 0
    fi

    if is_nonruntime_notice_file "$notice_file" "$rel"; then
        printf '%s\t%s\t%s\n' "$notice_package" "$rel" "non-runtime documentation notice excluded" >> "$skipped_nonruntime_notice_files_manifest"
        return 0
    fi

    if package_is_linked "$package"; then
        copy_notice_file "$notice_file" "$rel"
    else
        printf '%s\t%s\t%s\n' "$package" "$rel" "not present in linked-contrib-packages.txt" >> "$skipped_unlinked_notice_files_manifest"
    fi
}

{
    echo "VLCKit License Notice Bundle"
    echo
    echo "Generated at: $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
    echo "Project root: $project_root"
    echo "VLC root: $vlc_root"
    if [ -n "$evidence_root" ]; then
        echo "Binary evidence root: $evidence_root"
    fi
    echo
    if [ -d "$project_root/.git" ]; then
        echo "VLCKit git commit: $(git -C "$project_root" rev-parse HEAD 2>/dev/null || true)"
    fi
    if [ -d "$vlc_root/.git" ]; then
        echo "VLC git commit: $(git -C "$vlc_root" rev-parse HEAD 2>/dev/null || true)"
    fi
} > "$build_info"

copy_notice_file "$project_root/COPYING" "VLCKit-COPYING.txt"
copy_notice_file "$vlc_root/COPYING" "VLC-COPYING-GPL-2.0.txt"
copy_notice_file "$vlc_root/COPYING.LIB" "VLC-COPYING-LIB-LGPL-2.1.txt"

if [ -d "$vlc_root" ]; then
    while IFS= read -r static_list; do
        {
            echo "# $(relative_to_project "$static_list")"
            cat "$static_list"
            echo
        } >> "$static_libs_all"
    done < <(find "$vlc_root" -path '*/static-lib/static-libs-list' -type f | sort)
fi

if [ -s "$static_libs_all" ]; then
    awk '
        /^#/ || NF == 0 { next }
        {
            marker = "/contrib/"
            start = index($0, marker)
            if (start == 0 || $0 !~ /[.]a$/) {
                next
            }

            n = substr($0, start + length(marker))
            count = split(n, parts, "/")
            if (count >= 3 && parts[2] == "lib") {
                print parts[1] "\t" parts[count] "\t" $0
            }
        }
    ' "$static_libs_all" | sort -u > "$contrib_manifest"

    while IFS="$(printf '\t')" read -r _triplet library _path; do
        package_from_static_library "$library"
    done < "$contrib_manifest" | sort -u > "$linked_contrib_packages"

    awk '
        /^#/ || NF == 0 { next }
        {
            count = split($0, parts, "/")
            file = parts[count]
            if (file ~ /^lib.*_plugin[.]a$/) {
                sub(/^lib/, "", file)
                sub(/_plugin[.]a$/, "", file)
                print file
            }
        }
    ' "$static_libs_all" | sort -u > "$plugin_manifest"
fi

build_binary_evidence_index "$evidence_root"

if [ -d "$vlc_root/contrib" ]; then
    while IFS= read -r notice_file; do
        if ! is_collectable_notice_file "$notice_file"; then
            continue
        fi
        process_candidate_notice_file "$notice_file"
    done < <(
        find "$vlc_root/contrib" -type f \
            \( -iname 'COPYING' -o -iname 'COPYING.*' \
            -o -iname 'LICENSE' -o -iname 'LICENSE.*' \
            -o -iname 'NOTICE' -o -iname 'NOTICE.*' \
            -o -iname 'Copyright' -o -iname 'Copyright.*' \) \
            ! -path "$vlc_root/contrib/src/*" \
            ! -path "$vlc_root/contrib/tarballs/*" \
            | sort
    )
fi

if [ -d "$vlc_root" ]; then
    while IFS= read -r notice_file; do
        if ! is_collectable_notice_file "$notice_file"; then
            continue
        fi
        process_candidate_notice_file "$notice_file"
    done < <(
        find "$vlc_root" -maxdepth 3 -type f \
            \( -iname 'COPYING' -o -iname 'COPYING.*' \
            -o -iname 'LICENSE' -o -iname 'LICENSE.*' \
            -o -iname 'NOTICE' -o -iname 'NOTICE.*' \
            -o -iname 'Copyright' -o -iname 'Copyright.*' \) \
            ! -path "$vlc_root/contrib/*" \
            ! -path "$vlc_root/build*/*" \
            ! -path "$vlc_root/COPYING" \
            ! -path "$vlc_root/COPYING.LIB" \
            | sort
    )
fi

verify_no_gpl_only_linked_notice_gaps

{
    echo "VLCKit License Notices"
    echo "======================"
    echo
    echo "This bundle was generated from the VLCKit build workspace."
    echo "It includes the VLCKit license, VLC/libVLC license files, build manifests,"
    echo "and top-level license/notice files found in the built VLC contrib source/install trees."
    echo "License notices are copied as licenses/<name>.txt."
    echo "Nested bundled notices are split out only when the nested package is linked separately"
    echo "or observed in the generated framework/dSYM binary evidence."
    echo "When multiple non-GPL, non-documentation source files map to the same output name, they are concatenated."
    echo "Individual license files contain the original notice text without generated metadata."
    echo
    echo "Important files:"
    echo "- manifests/static-libs-list-all.txt: static libraries linked into libvlc-full-static.a"
    echo "- manifests/contrib-static-libraries.tsv: contrib static libraries observed in the link list"
    echo "- manifests/linked-contrib-packages.txt: contrib packages inferred from linked static libraries"
    echo "- manifests/vlc-static-plugins.txt: VLC static plugins observed in the link list"
    echo "- manifests/candidate-license-files.tsv: source license files considered for extraction"
    echo "- manifests/binary-evidence-files.txt: framework/dSYM files scanned for nested dependency evidence"
    echo "- manifests/nested-dependency-evidence.tsv: why nested bundled notices were included"
    echo "- manifests/license-files.tsv: source license files and their copied output path"
    echo "- manifests/skipped-unlinked-license-files.tsv: candidate files excluded because their package was not linked"
    echo "- manifests/skipped-gpl-license-files.tsv: GPL-only license files excluded for --disable-gpl builds"
    echo "- manifests/skipped-nonruntime-license-files.tsv: documentation-only notices excluded from runtime notices"
    echo "- manifests/gpl-only-linked-license-failures.tsv: fatal GPL-only linked/evidenced packages without non-GPL notices"
    echo "- VLCKit-LICENSES-THIRD-PARTY.txt: concatenated notice text for application bundling"
    echo
    if [ ! -s "$static_libs_all" ]; then
        echo "Warning: no static-libs-list files were found. Run this after the libVLC build"
        echo "and before cleaning libvlc/vlc/build-* if you need a precise linked-library manifest."
        echo
    fi
} > "$output_dir/README.txt"

{
    echo "VLCKit Third-Party License Notices"
    echo "=================================="
    echo
    cat "$output_dir/README.txt"
    echo
    echo "Build Information"
    echo "-----------------"
    cat "$build_info"
    echo

    while IFS= read -r notice_file; do
        echo
        echo "-------------------------------------------------------------------------------"
        echo "$(basename "$notice_file")"
        echo "-------------------------------------------------------------------------------"
        echo
        cat "$notice_file"
        echo
    done < <(find "$output_dir/licenses" -type f | sort)
} > "$combined_notice"

rm -f "$seen_notice_keys" "$binary_evidence_strings" "$binary_evidence_cache"

echo "License notices written to $output_dir"
